FormKey: 25ACE8:LastSeed.esp
EditorID: _Seed_ConfigMenuAlcoholDisease
Description:
  TargetLanguage: English
  Value: ALCOHOL & DISEASE
INAM: 0x00000000
Flags:
- MessageBox
MenuButtons:
- Text:
    TargetLanguage: English
    Value: Main Menu
- Text:
    TargetLanguage: English
    Value: Enable Alcohol
- Text:
    TargetLanguage: English
    Value: Alcohol Tripping
- Text:
    TargetLanguage: English
    Value: Random Pass Out
- Text:
    TargetLanguage: English
    Value: More
