FormKey: 255BDC:LastSeed.esp
EditorID: _Seed_ConfigMenuNeeds_Hunger
Description:
  TargetLanguage: English
  Value: >-
    ENABLE HUNGER


    Enable Hunger System


    Default: Enabled
INAM: 0x00000000
Flags:
- MessageBox
MenuButtons:
- Text:
    TargetLanguage: English
    Value: Back
- Text:
    TargetLanguage: English
    Value: 1. Disable
- Text:
    TargetLanguage: English
    Value: 2. Enable
