FormKey: 64580E:LastSeed.esp
EditorID: _Seed_ConfigMenuNeeds_Cannibalism
Description:
  TargetLanguage: English
  Value: >-
    ENABLE CANNIBALISM


    Allows you to restore your needs by feeding on corpses. Crouch down next to a corpse and activate it to start feeding. This option also works for vampires.


    Default: Disabled
INAM: 0x00000000
Flags:
- MessageBox
MenuButtons:
- Text:
    TargetLanguage: English
    Value: Back
- Text:
    TargetLanguage: English
    Value: 1. Disable
- Text:
    TargetLanguage: English
    Value: 2. Enable
