// GENERATED by tools/extract_mcm.py from Last Seed's own MCM script, LastSeed.esp and English strings. Do not edit by hand.
// Last Seed - Survival Needs and Diseases is by Chesko and Aytrus; its scripts and plugin are MIT licensed (the meshes and textures are not part of this).
#pragma once

namespace mcm
{
	enum class Kind { Header, Column, Toggle, Slider, Menu };

	// One row of a page. formId is the local FormID of the setting's global in LastSeed.esp (0 for headers and column breaks).
	// Toggles hold 1 (off) or 2 (on). A menu stores its list position plus menuBase. Sliders are saved to the profile as integers.
	struct Entry
	{
		Kind                kind;
		const char*         label;
		unsigned int        formId;
		const char*         profileKey;  // key in the profile file ("" when the setting is not saved to profiles)
		float               def, min, max, step;
		const char*         format;      // slider display format, e.g. {1} = one decimal
		const char* const*  options;     // menu entries
		int                 optionCount;
		int                 menuBase;    // value stored for the first menu entry
	};

	inline constexpr const char* kList_VampirismModeList[] = {
		"Mortal",
		"Supernatural",
		"Immortal",
	};
	inline constexpr const char* kList_followerModeList[] = {
		"Disabled",
		"Enabled",
	};
	inline constexpr const char* kList_followerCountList[] = {
		"Auto",
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
	};
	inline constexpr const char* kList_FoodNamesList[] = {
		"No",
		"Yes",
	};
	inline constexpr const char* kList_NoVitalityList[] = {
		"Nothing",
		"Rescue",
		"Death",
	};
	inline constexpr const char* kList_DiseasePotionModeList[] = {
		"Generic",
		"Unique",
		"No Cure",
	};
	inline constexpr const char* kList_SpoilageRemoveModeList[] = {
		"None",
		"Perished Only",
		"Moldy & Perished",
	};

	inline constexpr Entry kPage0[] = {
		{ Kind::Header, "General", 0, "", 0.0f, 0.0f, 0.0f, 0.0f, "", nullptr, 0, 0 },
		{ Kind::Toggle, "Enable Focus", 0x1EB653, "focus_enabled", 1, 1, 2, 1, "", nullptr, 0, 1 },
		{ Kind::Toggle, "Focus in Dungeons", 0x64070A, "DungeonFocus", 1, 1, 2, 1, "", nullptr, 0, 1 },
		{ Kind::Toggle, "Auto-Eat and Drink", 0x0B681C, "auto_consume", 1, 1, 2, 1, "", nullptr, 0, 1 },
		{ Kind::Toggle, "Enable Water Bottles", 0x636507, "EnableWaterBottles", 1, 1, 2, 1, "", nullptr, 0, 1 },
		{ Kind::Toggle, "Innkeepers Refill Waterskins", 0x663E2D, "InnDialogWater", 1, 1, 2, 1, "", nullptr, 0, 1 },
		{ Kind::Toggle, "Innkeepers Sell Meals", 0x663E2E, "InnDialogMeals", 1, 1, 2, 1, "", nullptr, 0, 1 },
		{ Kind::Toggle, "Alternative Death System", 0x5CBFE6, "Advanced_AlternativeDeath", 1, 1, 2, 1, "", nullptr, 0, 1 },
		{ Kind::Toggle, "Enable Cannibalism", 0x612DFA, "Cannibalism", 1, 1, 2, 1, "", nullptr, 0, 1 },
		{ Kind::Menu, "Vampire Behavior:", 0x0029D1, "vampire_mode", 1.0f, 0.0f, 0.0f, 0.0f, "", kList_VampirismModeList, 3, 1 },
		{ Kind::Toggle, "Player is Lich", 0x58A11C, "", 1, 1, 2, 1, "", nullptr, 0, 1 },
		{ Kind::Column, "", 0, "", 0, 0, 0, 0, "", nullptr, 0, 0 },
		{ Kind::Header, "Followers", 0, "", 0.0f, 0.0f, 0.0f, 0.0f, "", nullptr, 0, 0 },
		{ Kind::Menu, "Needs Affect Followers", 0x0CAC33, "FollowerNeeds_enabled", 1.0f, 0.0f, 0.0f, 0.0f, "", kList_followerModeList, 2, 1 },
		{ Kind::Menu, "Party Size", 0x3E5C4B, "FollowerNeeds_count", 0.0f, 0.0f, 0.0f, 0.0f, "", kList_followerCountList, 11, 0 },
		{ Kind::Slider, "Provisions Per Person", 0x0C0A23, "Advanced_ProvisionsWeight", 25.0f, 1.0f, 300.0f, 1.0f, "{0}", nullptr, 0, 0 },
		{ Kind::Toggle, "Follower Food Effects", 0x431B7F, "followersConsume", 1, 1, 2, 1, "", nullptr, 0, 1 },
		{ Kind::Toggle, "Serana Drinks Blood Potions", 0x68C647, "", 1, 1, 2, 1, "", nullptr, 0, 1 },
		{ Kind::Header, "Food Properties", 0, "", 0.0f, 0.0f, 0.0f, 0.0f, "", nullptr, 0, 0 },
		{ Kind::Slider, "Food Weight", 0x2CF455, "FoodWeight", 1.0f, 0.0f, 5.0f, 0.1f, "{1}", nullptr, 0, 0 },
		{ Kind::Slider, "Food Price", 0x2CF454, "FoodPrice", 1.0f, 0.0f, 5.0f, 0.1f, "{1}", nullptr, 0, 0 },
		{ Kind::Menu, "Descriptive Food Names", 0x3348F6, "food_names", 1.0f, 0.0f, 0.0f, 0.0f, "", kList_FoodNamesList, 2, 1 },
	};

	inline constexpr Entry kPage1[] = {
		{ Kind::Header, "General", 0, "", 0.0f, 0.0f, 0.0f, 0.0f, "", nullptr, 0, 0 },
		{ Kind::Toggle, "Needs Affected by Regeneration", 0x36731B, "regeneration", 1, 1, 2, 1, "", nullptr, 0, 1 },
		{ Kind::Toggle, "Needs Affect Movement", 0x209C6B, "thirst_affects_movement", 1, 1, 2, 1, "", nullptr, 0, 1 },
		{ Kind::Header, "Hunger", 0, "", 0.0f, 0.0f, 0.0f, 0.0f, "", nullptr, 0, 0 },
		{ Kind::Toggle, "Enable Hunger", 0x007073, "hunger_enabled", 1, 1, 2, 1, "", nullptr, 0, 1 },
		{ Kind::Slider, "Hunger Rate", 0x0513F8, "HungerRate", 1.0f, 0.1f, 5.0f, 0.1f, "{1}", nullptr, 0, 0 },
		{ Kind::Toggle, "Diminishing Returns", 0x00C70F, "diminishing_returns", 1, 1, 2, 1, "", nullptr, 0, 1 },
		{ Kind::Column, "", 0, "", 0, 0, 0, 0, "", nullptr, 0, 0 },
		{ Kind::Header, "Thirst", 0, "", 0.0f, 0.0f, 0.0f, 0.0f, "", nullptr, 0, 0 },
		{ Kind::Toggle, "Enable Thirst", 0x007074, "thirst_enabled", 1, 1, 2, 1, "", nullptr, 0, 1 },
		{ Kind::Slider, "Thirst Rate", 0x0513F9, "ThirstRate", 1.0f, 0.1f, 5.0f, 0.1f, "{1}", nullptr, 0, 0 },
		{ Kind::Header, "Fatigue", 0, "", 0.0f, 0.0f, 0.0f, 0.0f, "", nullptr, 0, 0 },
		{ Kind::Toggle, "Enable Fatigue", 0x007075, "fatigue_enabled", 1, 1, 2, 1, "", nullptr, 0, 1 },
		{ Kind::Slider, "Fatigue Rate", 0x0513F7, "FatigueRate", 1.0f, 0.1f, 5.0f, 0.1f, "{1}", nullptr, 0, 0 },
		{ Kind::Toggle, "Sleep Affected by Needs", 0x1BDD1E, "sleep_needs", 1, 1, 2, 1, "", nullptr, 0, 1 },
		{ Kind::Toggle, "Sleep Affected by Location", 0x1BDD1F, "sleep_location", 1, 1, 2, 1, "", nullptr, 0, 1 },
	};

	inline constexpr Entry kPage2[] = {
		{ Kind::Header, "Vitality", 0, "", 0.0f, 0.0f, 0.0f, 0.0f, "", nullptr, 0, 0 },
		{ Kind::Toggle, "Enable Vitality", 0x007076, "vitality_enabled", 1, 1, 2, 1, "", nullptr, 0, 1 },
		{ Kind::Slider, "Vitality Rate", 0x05B5FC, "VitalityRate", 1.0f, 0.1f, 5.0f, 0.1f, "{1}", nullptr, 0, 0 },
		{ Kind::Menu, "At Zero Vitality", 0x209C6C, "no_vitality_mode", 0.0f, 0.0f, 0.0f, 0.0f, "", kList_NoVitalityList, 3, 1 },
		{ Kind::Column, "", 0, "", 0, 0, 0, 0, "", nullptr, 0, 0 },
		{ Kind::Header, "Vitality Impact Multipliers", 0, "", 0.0f, 0.0f, 0.0f, 0.0f, "", nullptr, 0, 0 },
		{ Kind::Slider, "Hunger Multiplier", 0x33EB0B, "VitalityMultiHunger", 1.0f, 0.1f, 3.0f, 0.1f, "{1}", nullptr, 0, 0 },
		{ Kind::Slider, "Thirst Multiplier", 0x33EB0A, "VitalityMultiThirst", 1.0f, 0.1f, 3.0f, 0.1f, "{1}", nullptr, 0, 0 },
		{ Kind::Slider, "Fatigue Multiplier", 0x33EB08, "VitalityMultiFatigue", 1.0f, 0.1f, 3.0f, 0.1f, "{1}", nullptr, 0, 0 },
		{ Kind::Slider, "Disease Multiplier", 0x33EB09, "VitalityMultiDisease", 1.0f, 0.1f, 3.0f, 0.1f, "{1}", nullptr, 0, 0 },
		{ Kind::Slider, "Exposure Multiplier", 0x33EB07, "VitalityMultiExposure", 1.0f, 0.1f, 3.0f, 0.1f, "{1}", nullptr, 0, 0 },
	};

	inline constexpr Entry kPage3[] = {
		{ Kind::Header, "Alcohol and Skooma", 0, "", 0.0f, 0.0f, 0.0f, 0.0f, "", nullptr, 0, 0 },
		{ Kind::Toggle, "Enable Acohol", 0x01082F, "alcohol_enabled", 1, 1, 2, 1, "", nullptr, 0, 1 },
		{ Kind::Slider, "Alcohol Rate", 0x3EFE4E, "AlcoholRate", 1.0f, 0.1f, 5.0f, 0.1f, "{1}", nullptr, 0, 0 },
		{ Kind::Toggle, "Enable Skooma", 0x2A6C32, "skooma_enabled", 1, 1, 2, 1, "", nullptr, 0, 1 },
		{ Kind::Slider, "Skooma Rate", 0x3EFE4F, "SkoomaRate", 1.0f, 0.1f, 5.0f, 0.1f, "{1}", nullptr, 0, 0 },
		{ Kind::Slider, "Alcohol Strength - Ale", 0x209C6D, "Alcohol_RateAle", 1.0f, 0.1f, 5.0f, 0.1f, "{1}", nullptr, 0, 0 },
		{ Kind::Slider, "Alcohol Strength - Wine", 0x209C6E, "Alcohol_RateWine", 1.0f, 0.1f, 5.0f, 0.1f, "{1}", nullptr, 0, 0 },
		{ Kind::Slider, "Alcohol Strength - Spirits", 0x209C6F, "Alcohol_RateSpirits", 1.0f, 0.1f, 5.0f, 0.1f, "{1}", nullptr, 0, 0 },
		{ Kind::Slider, "Skooma Strength - Weak", 0x2A6C2F, "Skooma_RateWeak", 1.0f, 0.1f, 5.0f, 0.1f, "{1}", nullptr, 0, 0 },
		{ Kind::Slider, "Skooma Strength - Strong", 0x2A6C30, "Skooma_RateStrong", 1.0f, 0.1f, 5.0f, 0.1f, "{1}", nullptr, 0, 0 },
		{ Kind::Toggle, "Drunk & Addiction Stumbling", 0x2A1B28, "alcohol_stumbling", 1, 1, 2, 1, "", nullptr, 0, 1 },
		{ Kind::Toggle, "Change Location on Pass Out", 0x654B1F, "drunken_shenanigans", 1, 1, 2, 1, "", nullptr, 0, 1 },
		{ Kind::Column, "", 0, "", 0, 0, 0, 0, "", nullptr, 0, 0 },
		{ Kind::Header, "Diseases", 0, "", 0.0f, 0.0f, 0.0f, 0.0f, "", nullptr, 0, 0 },
		{ Kind::Toggle, "Progressive Diseases", 0x010835, "disease_enabled", 1, 1, 2, 1, "", nullptr, 0, 1 },
		{ Kind::Toggle, "Additional Diseases", 0x59E56D, "additional_diseases", 1, 1, 2, 1, "", nullptr, 0, 1 },
		{ Kind::Toggle, "Shrines Increase Disease Resistance", 0x2468C4, "shrines", 1, 1, 2, 1, "", nullptr, 0, 1 },
		{ Kind::Toggle, "Priests Cure Diseases", 0x35D117, "priests", 1, 1, 2, 1, "", nullptr, 0, 1 },
		{ Kind::Menu, "Cure Disease Potion Behaviour", 0x209C73, "disease_potion_mode", 1.0f, 0.0f, 0.0f, 0.0f, "", kList_DiseasePotionModeList, 3, 1 },
		{ Kind::Slider, "Raw Food Disease Chance", 0x209C70, "Disease_ChanceRawFood", 15.0f, 0.0f, 100.0f, 5.0f, "{0}", nullptr, 0, 0 },
		{ Kind::Slider, "Stale Food Disease Chance", 0x209C72, "Disease_ChanceStaleFood", 15.0f, 0.0f, 100.0f, 5.0f, "{0}", nullptr, 0, 0 },
		{ Kind::Slider, "Dirty Water Disease Chance", 0x209C71, "Disease_ChanceDirtyWater", 15.0f, 0.0f, 100.0f, 5.0f, "{0}", nullptr, 0, 0 },
	};

	inline constexpr Entry kPage4[] = {
		{ Kind::Header, "Food Spoilage Options", 0, "", 0.0f, 0.0f, 0.0f, 0.0f, "", nullptr, 0, 0 },
		{ Kind::Toggle, "Food Spoils", 0x204B66, "Spoilage_enabled", 1, 1, 2, 1, "", nullptr, 0, 1 },
		{ Kind::Menu, "Remove Perished Food", 0x2E8991, "Spoilage_remove", 1.0f, 0.0f, 0.0f, 0.0f, "", kList_SpoilageRemoveModeList, 3, 1 },
		{ Kind::Toggle, "Spoilage affected by temperature", 0x427973, "Spoilage_temperature", 1, 1, 2, 1, "", nullptr, 0, 1 },
		{ Kind::Header, "Food Spoilage Rates", 0, "", 0.0f, 0.0f, 0.0f, 0.0f, "", nullptr, 0, 0 },
		{ Kind::Slider, "Bread", 0x20ED75, "Spoilage_Bread", 168.0f, 1.0f, 400.0f, 1.0f, "{0}", nullptr, 0, 0 },
		{ Kind::Slider, "Raw Meat", 0x20ED76, "Spoilage_MeatRaw", 24.0f, 1.0f, 400.0f, 1.0f, "{0}", nullptr, 0, 0 },
		{ Kind::Slider, "Cooked Meat", 0x20ED77, "Spoilage_MeatCooked", 60.0f, 1.0f, 400.0f, 1.0f, "{0}", nullptr, 0, 0 },
		{ Kind::Slider, "Raw Small Game", 0x20ED78, "Spoilage_SmallGameRaw", 24.0f, 1.0f, 400.0f, 1.0f, "{0}", nullptr, 0, 0 },
		{ Kind::Slider, "Cooked Small Game", 0x20ED79, "Spoilage_SmallGameCooked", 60.0f, 1.0f, 400.0f, 1.0f, "{0}", nullptr, 0, 0 },
		{ Kind::Slider, "Raw Fish", 0x20ED7A, "Spoilage_FishRaw", 24.0f, 1.0f, 400.0f, 1.0f, "{0}", nullptr, 0, 0 },
		{ Kind::Slider, "Cooked Fish", 0x20ED7B, "Spoilage_FishCooked", 60.0f, 1.0f, 400.0f, 1.0f, "{0}", nullptr, 0, 0 },
		{ Kind::Column, "", 0, "", 0, 0, 0, 0, "", nullptr, 0, 0 },
		{ Kind::Header, "Food Spoilage Rates (Continued)", 0, "", 0.0f, 0.0f, 0.0f, 0.0f, "", nullptr, 0, 0 },
		{ Kind::Slider, "Raw Seafood", 0x20ED7C, "Spoilage_SeafoodRaw", 24.0f, 1.0f, 400.0f, 1.0f, "{0}", nullptr, 0, 0 },
		{ Kind::Slider, "Cooked Seafood", 0x20ED7D, "Spoilage_SeafoodCooked", 60.0f, 1.0f, 400.0f, 1.0f, "{0}", nullptr, 0, 0 },
		{ Kind::Slider, "Vegetables", 0x20ED7E, "Spoilage_Vegetables", 120.0f, 1.0f, 400.0f, 1.0f, "{0}", nullptr, 0, 0 },
		{ Kind::Slider, "Fruit", 0x20ED7F, "Spoilage_Fruit", 120.0f, 1.0f, 400.0f, 1.0f, "{0}", nullptr, 0, 0 },
		{ Kind::Slider, "Cheese", 0x20ED80, "Spoilage_Cheese", 120.0f, 1.0f, 400.0f, 1.0f, "{0}", nullptr, 0, 0 },
		{ Kind::Slider, "Treats", 0x20ED81, "Spoilage_Treats", 168.0f, 1.0f, 400.0f, 1.0f, "{0}", nullptr, 0, 0 },
		{ Kind::Slider, "pastries", 0x20ED82, "Spoilage_Pastries", 120.0f, 1.0f, 400.0f, 1.0f, "{0}", nullptr, 0, 0 },
		{ Kind::Slider, "Stew", 0x20ED83, "Spoilage_Stews", 120.0f, 1.0f, 400.0f, 1.0f, "{0}", nullptr, 0, 0 },
		{ Kind::Slider, "Cheese Bowls", 0x20ED84, "Spoilage_CheeseBowls", 120.0f, 1.0f, 400.0f, 1.0f, "{0}", nullptr, 0, 0 },
		{ Kind::Slider, "Milk", 0x20ED85, "Spoilage_DrinkMilk", 120.0f, 1.0f, 400.0f, 1.0f, "{0}", nullptr, 0, 0 },
		{ Kind::Slider, "Ice Wraith Powder", 0x450191, "Spoilage_IceWraithTeeth", 36.0f, 1.0f, 400.0f, 1.0f, "{0}", nullptr, 0, 0 },
	};

	struct Page
	{
		const char*  title;
		const Entry* entries;
		int          count;
	};
	inline constexpr Page kPages[] = {
		{ "Gameplay", kPage0, static_cast<int>(std::size(kPage0)) },
		{ "Needs", kPage1, static_cast<int>(std::size(kPage1)) },
		{ "Vitality", kPage2, static_cast<int>(std::size(kPage2)) },
		{ "Alcohol, Skooma & Disease", kPage3, static_cast<int>(std::size(kPage3)) },
		{ "Food Spoilage", kPage4, static_cast<int>(std::size(kPage4)) },
	};
}
